os: linux
dist: bionic
language: python
python:
  - '3.8'
services:
  - docker
before_install:
  - touch .env
  - echo ${DB_NAME} >> .env
  - echo ${DB_USER} >> .env
  - echo ${DB_PASS} >> .env
  - echo ${DB_HOST} >> .env
  - echo ${DB_PORT} >> .env
  - echo ${POSTGRES_USER} >> .env
  - echo ${POSTGRES_PASSWORD} >> .env
  - echo ${POSTGRES_DB} >> .env
install:
  - pip install docker-compose
before_script:
  - docker-compose build
script:
  - docker-compose run --rm django coverage run --source=. manage.py test -v2
notifications:
  email:
    on_success: never
    on_failure: always
