os: linux
dist: bionic
language: python
python:
  - '3.8'
services:
  - postgresql
install:
  - pip install tox
before_script:
  - createuser -U postgres -d travelproject --superuser
  - createdb -U postgres -O travelproject travelproject
script:
  - tox
notifications:
  email:
    on_success: never
    on_failure: always
