os: linux
dist: bionic
language: python
python:
  - '3.8'
services:
  - docker
script:
  - docker-compose run --rm django coverage run --source=. manage.py test -v2
notifications:
  email:
    on_success: never
    on_failure: always
