name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create .env
        run: mv .env.example .env

      - name: Build the project
        run: docker-compose build
          
      - name: Format code with black
        run: docker-compose run django black . --check

      - name: Format code with flake8
        run: docker-compose run django flake8

      - name: Type check
        run: docker-compose run django mypy --config mypy.ini travelproject/